---
title: "Activity2Stat380"
output: html_document
date: "2023-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages used in this guide ----
packages <- c("tidyverse", "knitr", "kableExtra", "leaps")

invisible(
  lapply(
    X = packages,
    FUN = library,
    character.only = TRUE,
    quietly = TRUE
  )
)

# Set Table Option ----
options(knitr.kable.NA = "")
```

```{r}
activity2_insurance <- read.csv("activity2_insurance.csv")
```

```{r}
View(activity2_insurance)
```


```{r}
activity2_insurance %>%
  ggplot(
    mapping = aes(x = bmi, y = charges, color = sex)
  ) +
  geom_point(size = 0.5) +
  facet_grid(rows = vars(region), cols = vars(smoker))
```
```{r}
activity2_insurance$sex <- as.factor(activity2_insurance$sex)
activity2_insurance$region <- as.factor(activity2_insurance$region)
activity2_insurance$smoker <- as.factor(activity2_insurance$smoker)
```


```{r}
first_model <- lm(
  formula = charges ~ smoker,age,children,
  data = activity2_insurance,
  na.action = "na.omit"
)
```


```{r}
summary(first_model)
```


```{r}

```